### PR TITLE
Replace Kuka meshes in lwr_sdh.urdf

### PR DESCRIPTION
**Pull request by christian-rauch**
This PR replaces the meshes for the Kuka. It's only applied to the `lwr_sdh.urdf` so far.

Old meshes:
kuka_meshes_old
kuka_old

New meshes:
kuka_meshes_new
kuka_new

### CODE REVIEW

**Comment by VladimirIvan** [comment]
Can you remove the matlab files and propagate the new meshes into all the URDF and XACRO files?

**Comment by christian-rauch** [comment]
How were the URDFs initially generated? Is it possible to apply the changes to the xacro file `kuka_lwr_arm_defs.xml` and generated the URDFs with the individual end-effectors?

**Comment by wxmerkt** [comment]
Unfortunately lots of them are copy and paste so if they could be moved to xacro, that would be an advantage. Also can we squash after to keep the repository clean of temporary binary files? :-)

**Comment by VladimirIvan** [comment]
I think I ran the XACRO from the command line and then just manually added the different end-effectors, if I was clever enough to do that back then. If not, they were just copied and manually edited.
A XACRO solution would be best though.

**Comment by wxmerkt** [comment]
This has been merged despite Vlad's earlier comments not being addressed. Particularly:

- Not properly propagated the meshes to other URDFs (but old STLs still included so not breaking)
- Adoption/fixing of URDFs with xacro and generation on compile time.

**Comment by christian-rauch** [comment]
I am currently applying the changes to the xacro files. I will write a scripts that generates the URDF (kuka+tools) from the xacro files.

**Comment by wxmerkt** [comment]
Thank you. You can in the CMakeLists ``find_package(catkin REQUIRED COMPONENTS xacro)`` and then ``xacro_add_files(list of xacros INORDER INSTALL)`` which creates the URDFs and installs them to both devel and install.

**Comment by christian-rauch** [comment]
Yeah. I checked http://wiki.ros.org/xacro#Building_from_CMakeLists.txt to generate the URDFs at install time. So far I only managed to install them to `install` via `catkin install` + `catkin build`. But I could not achieve to have them placed in the devel space via a regular `catkin build`.
Let's check again once I have a new PR on this.

**Pull request merged**
