### PR TITLE
 Addresses issue #11

### PR DESCRIPTION
**Pull request by ferrolho**
- Adds some missing .obj meshes
- Addresses issue #11 (corrects joint effort definitions)

### CODE REVIEW

**Comment by wxmerkt** [comment]
Is there a need for the obj? Most viewers (including meshcat, I added that a while back) support dae now.

**Comment by ferrolho** [comment]
img

**Comment by wxmerkt** [comment]
None of the URDFs uses .obj directly. This is an issue with Mechanisms in Julia - you can make an upstream PR to fix it (by using the dae and stl support I added to MeshCat a few months back).

**Comment by wxmerkt** [comment]
Here is the upstream issue in the `MechanismGeometries.jl` package:

https://github.com/JuliaRobotics/MechanismGeometries.jl/blob/f9c4f1ce16a90e06da5b4fca45c9be589993e9cb/src/urdf.jl#L40-L47

and here is a filed upstream issue: https://github.com/JuliaRobotics/MechanismGeometries.jl/issues/12

**Comment by ferrolho** [comment]
I have removed the `.obj` from this PR.

**Pull request merged**
